# -*- coding: utf-8 -*-
"""patch_llvcols.py - llv_sheet doc cot theo TEN header (ben vung khi sheet xe dich cot).
Tab T7 chen them cot [0] 'NOI KHOA/NGOAI KHOA' -> moi cot +1 -> code cu doc trat -> noshow toan bo.
Idempotent."""
import io, sys
PATH = sys.argv[1] if len(sys.argv) > 1 else 'llv_sheet.py'
src = io.open(PATH, encoding='utf-8').read()
if '# [llvcols]' in src:
    print('Da patch roi ([llvcols]) - bo qua.'); sys.exit(0)

OLD_CONST = (
    "# vi tri cot (0-based)\n"
    "C_SALE, C_NGUON, C_LOAI, C_NGAYCHOT = 0, 1, 2, 3\n"
    "C_TEN, C_SDT, C_SL, C_DV = 4, 5, 6, 7\n"
    "C_NGAYHEN, C_TRANGTHAI, C_NHAC = 12, 14, 15\n"
)
NEW_CONST = (
    "# vi tri cot MAC DINH (0-based) - chi dung khi khong do duoc theo ten header\n"
    "C_SALE, C_NGUON, C_LOAI, C_NGAYCHOT = 1, 2, 3, 4\n"
    "C_TEN, C_SDT, C_SL, C_DV = 5, 6, 7, 8\n"
    "C_NGAYHEN, C_TRANGTHAI, C_NHAC = 13, 15, 16\n"
    "\n"
    "# [llvcols] Do cot theo TEN header -> ben vung khi sheet them/bot/xe dich cot.\n"
    "def _hn(h):\n"
    "    h = unicodedata.normalize('NFKD', str(h))\n"
    "    h = ''.join(c for c in h if not unicodedata.combining(c))\n"
    "    return ' '.join(h.lower().split())   # gom moi khoang trang (\\n \\xa0...) ve 1 space\n"
    "def _find_cols(header):\n"
    "    H = [_hn(h) for h in header]\n"
    "    def find(*keys):\n"
    "        for i, h in enumerate(H):\n"
    "            if h and any(k in h for k in keys):\n"
    "                return i\n"
    "        return None\n"
    "    c = {}\n"
    "    c['nguon']     = find('nguon')\n"
    "    c['loai']      = find('loai khach', 'loai')\n"
    "    c['ngaychot']  = find('ngay chot', 'chot')\n"
    "    c['ten']       = find('ho va ten', 'ho ten', 'ten')\n"
    "    c['sdt']       = find('dien thoai', 'so dt', 'sdt')\n"
    "    c['sl']        = find('sl khach', 'sl')\n"
    "    c['dv']        = find('dich vu')          # 'DICH VU' dau tien\n"
    "    c['thoigian']  = find('thoi gian')\n"
    "    c['master']    = find('bac si', 'master', 'ktv')\n"
    "    c['trangthai'] = find('trang thai', 'tinh trang')\n"
    "    c['nhac']      = find('nhac lich', 'nhac')\n"
    "    # 2 cot header TRONG -> suy theo hang xom co ten:\n"
    "    c['sale']    = (c['nguon'] - 1) if c['nguon'] else C_SALE   # cot ngay truoc NGUON\n"
    "    if c['master'] is not None:     c['ngayhen'] = c['master'] - 1   # cot ngay truoc BAC SI-MASTER\n"
    "    elif c['thoigian'] is not None: c['ngayhen'] = c['thoigian'] + 1\n"
    "    else:                           c['ngayhen'] = C_NGAYHEN\n"
    "    # fallback mac dinh neu thieu ten\n"
    "    _fb = {'sale':C_SALE,'nguon':C_NGUON,'loai':C_LOAI,'ngaychot':C_NGAYCHOT,'ten':C_TEN,\n"
    "           'sdt':C_SDT,'sl':C_SL,'dv':C_DV,'ngayhen':C_NGAYHEN,'trangthai':C_TRANGTHAI,'nhac':C_NHAC}\n"
    "    for k, v in _fb.items():\n"
    "        if c.get(k) is None: c[k] = v\n"
    "    return c\n"
)

OLD_LOAD = (
    "    width = 16\n"
    "    rows = []\n"
    "    cur_day = pd.NaT   # ngay tu dong ngan gan nhat (de ffill khi cot 12 trong)\n"
    "    for r in values[1:]:               # values[0] = header\n"
    "        r = list(r) + [\"\"] * (width - len(r))\n"
    "        r = r[:width]\n"
    "        if _is_separator(r):\n"
    "            cur_day = _vn_date(r[C_SALE], year)\n"
    "            continue\n"
    "        ten = (r[C_TEN] or \"\").strip()\n"
    "        sdt = (r[C_SDT] or \"\").strip()\n"
    "        if not ten and not sdt:\n"
    "            continue                    # dong trong\n"
    "        hen = _vn_date(r[C_NGAYHEN], year)\n"
    "        if pd.isna(hen):\n"
    "            hen = cur_day               # ffill tu dong ngan ngay\n"
    "        rows.append(dict(\n"
    "            sale=map_sale(r[C_SALE]),\n"
    "            nguon=(r[C_NGUON] or \"\").strip() or None,\n"
    "            loai_khach=(r[C_LOAI] or \"\").strip() or None,\n"
    "            ngay_chot=_vn_date(r[C_NGAYCHOT], year),\n"
    "            ten=ten or None,\n"
    "            phone=norm_phone(r[C_SDT]),\n"
    "            sl=(r[C_SL] or \"\").strip() or None,\n"
    "            dich_vu=(r[C_DV] or \"\").strip() or None,\n"
    "            ngay_hen=hen,\n"
    "            trang_thai_raw=(r[C_TRANGTHAI] or \"\").strip() or None,\n"
    "            nhac_lich=(r[C_NHAC] or \"\").strip() or None,\n"
    "            status=parse_status(r[C_TRANGTHAI], r[C_NHAC]),\n"
    "        ))\n"
    "    df = pd.DataFrame(rows)\n"
    "    return df\n"
)
NEW_LOAD = (
    "    # [llvcols] do cot theo ten header cua CHINH tab nay\n"
    "    C = _find_cols(values[0])\n"
    "    width = max(len(values[0]), max(C.values()) + 1, 18)\n"
    "    rows = []\n"
    "    cur_day = pd.NaT   # ngay tu dong gan nhat (ffill khi 1 dong thieu ngay hen)\n"
    "    for r in values[1:]:               # values[0] = header\n"
    "        r = list(r) + [\"\"] * (width - len(r))\n"
    "        r = r[:width]\n"
    "        ten = (r[C['ten']] or \"\").strip()\n"
    "        sdt = (r[C['sdt']] or \"\").strip()\n"
    "        if not ten and not sdt:\n"
    "            d = _vn_date(r[C['ngayhen']], year)   # dong ngan/trong: cap nhat ngay neu co\n"
    "            if pd.notna(d): cur_day = d\n"
    "            continue                              # dong trong\n"
    "        hen = _vn_date(r[C['ngayhen']], year)\n"
    "        if pd.isna(hen):\n"
    "            hen = cur_day               # ffill tu dong gan nhat\n"
    "        rows.append(dict(\n"
    "            sale=map_sale(r[C['sale']]),\n"
    "            nguon=(r[C['nguon']] or \"\").strip() or None,\n"
    "            loai_khach=(r[C['loai']] or \"\").strip() or None,\n"
    "            ngay_chot=_vn_date(r[C['ngaychot']], year),\n"
    "            ten=ten or None,\n"
    "            phone=norm_phone(r[C['sdt']]),\n"
    "            sl=(r[C['sl']] or \"\").strip() or None,\n"
    "            dich_vu=(r[C['dv']] or \"\").strip() or None,\n"
    "            ngay_hen=hen,\n"
    "            trang_thai_raw=(r[C['trangthai']] or \"\").strip() or None,\n"
    "            nhac_lich=(r[C['nhac']] or \"\").strip() or None,\n"
    "            status=parse_status(r[C['trangthai']], r[C['nhac']]),\n"
    "        ))\n"
    "    df = pd.DataFrame(rows)\n"
    "    return df\n"
)

for label, old in (('CONST', OLD_CONST), ('LOAD', OLD_LOAD)):
    if src.count(old) != 1:
        print('LOI: anchor %s xuat hien %d lan (can 1). Dung.' % (label, src.count(old))); sys.exit(2)
src = src.replace(OLD_CONST, NEW_CONST).replace(OLD_LOAD, NEW_LOAD)
io.open(PATH, 'w', encoding='utf-8').write(src)
print('OK: da patch %s (doc cot theo ten header).' % PATH)
